### ISSUE TITLE
Add xoak and fastparquet to environment?

### ISSUE THREAD

**Issue by rsignell** [microsoft/PlanetaryComputer#294]
Any chance to add `xoak` and `fastparquet` to the Planetary Computer hub environment? 
We have [a notebook  that shows how to explore the USGS CONUS404 simulation](https://github.com/fs-jbzambon/opendata-coawst/blob/main/COAWST_explore.ipynb), and I'd love to point people to the Planetary Computer hub as a place they could run it (using Dask gateway to speed things up).  

The notebook uses:
*  `xoak` for lon/lat point selection ( the lon/lat coords are 2D and there is no projected x,y coordinates). 
* `fastparquet` to read references generated by Kerchunk

**Comment by TomAugspurger** [comment]
Hi Rich. I'll look into adding those next time I update the environments.

I think we had fastparquet in the past, but had to remove it thanks to a package conflict. We do have pyarrrow.parquet, if that works for parquet reading.

**Comment by rsignell** [comment]
Ah, okay -- I'll check with @martindurant about why `fsspec` is complaining about needing `fastparquet` to read the references when `pyarrow.parquet` exists.

**Comment by martindurant** [comment]
I have used fastparquet for referenceFS explicitly because:
- it has helped rapid development to work with an API I know well (and is simpler, at least for me)
- it is a much smaller install dependency
- it is probably faster for this data (although this is untested and may not be significant)

I am surprised that fastparquet could conflict with anything - it's even been built for wasm.
```
pandas>=1.5.0
numpy>=1.20.3
cramjam>=2.3  # has no downstream deps
fsspec
packaging
```

**Comment by martindurant** [comment]
(having said all that, it may be reasonable at this point to relax the parquet backend requirement)

**Comment by ghidalgo3** [comment]
The hub is no longer available.
