### ISSUE TITLE
Connect to Google Drive

### ISSUE THREAD

**Issue by 007anupamdas** [microsoft/PlanetaryComputer#30]
My Deep Learning datasets are stored in Google Drive, of size 1.2 TB. I tried to access the Jupyterlab-GoogleDrive extension, but that is outdated. Is there any possibility to mount google drive, just like Colab pro. If I try using python-apis like pydrive/google-api etc. , I would need to download my dataset, then upload my training performances back, which is not feasible due to storage limits in Planetary Hub.
 I am trying to switch from Colab Pro, but these limitations are hindering me.

**Comment by TomAugspurger** [comment]
It's worth testing, but I expect that the bandwidth you'll get from Google Drive will be too slow to be usable. The exact method of connection / accessing the data probably doesn't matter as much.

You might be best off locating your compute next to your data, either by moving your compute (back) to Colab or by moving your data to something like Azure Blob Storage.

**Comment by TomAugspurger** [comment]
@007anupamdas did you have a chance to try out the performance accessing data from google drive?

> which is not feasible due to storage limits in Planetary Hub.

I forgot to mention: there should be more space outside of your home directory. Not 1.2 TB, but perhaps enough for a batch of data.

Closing this, since I don't think there's any concrete action items right now.
